admin/views.py
# IMPORTS
import copy
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from app import db, requires_roles
from models import User, Draw

# CONFIG
admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


# VIEWS
# view admin homepage
@admin_blueprint.route('/admin')
@login_required
@requires_roles('admin')
def admin():
    return render_template('admin.html', name=current_user.firstname)


# view all registered users
@admin_blueprint.route('/view_all_users', methods=['POST'])
@login_required
@requires_roles('admin')
def view_all_users():
    if not User.query.filter_by(role='user').all():
        # if no users registered, rerender admin page
        flash("There is no user registered.")
        return admin()
    return render_template('admin.html', name=current_user.firstname,
                           current_users=User.query.filter_by(role='user').all())


# create a new winning draw
@admin_blueprint.route('/create_winning_draw', methods=['POST'])
@login_required
@requires_roles('admin')
def create_winning_draw():
    # get current winning draw
    current_winning_draw = Draw.query.filter_by(win=True).first()
    round = 1

    # if a current winning draw exists
    if current_winning_draw:
        # update lottery round by 1
        round = current_winning_draw.round + 1

        # delete current winning draw
        db.session.delete(current_winning_draw)
        db.session.commit()

    # get new winning draw entered in form
    submitted_draw = ''
    for i in range(6):
        submitted_draw += request.form.get('no' + str(i + 1)) + ' '
    # remove any surrounding whitespace
    submitted_draw.strip()

    # create a new draw object with the form data.
    new_winning_draw = Draw(user_id=current_user.id, draw=submitted_draw, win=True, round=round,
                            draw_key=current_user.draw_key)

    # add the new winning draw to the database
    db.session.add(new_winning_draw)
    db.session.commit()

    # re-render admin page
    flash("New winning draw added.")
    return admin()


# view current winning draw
@admin_blueprint.route('/view_winning_draw', methods=['POST'])
@login_required
@requires_roles('admin')
def view_winning_draw():
    # get winning draw from DB
    current_winning_draw = Draw.query.filter_by(win=True).first()

    # if a winning draw exists
    if current_winning_draw:
        # creates a copied draw object which are independent of database.
        current_winning_draw_copy = copy.deepcopy(current_winning_draw)
        # decrypt the copied draw object.
        user = User.query.filter_by(id=current_winning_draw.user_id).first()
        current_winning_draw_copy.view_draw(user.draw_key)
        # re-render admin page with current winning draw and lottery round
        return render_template('admin.html', winning_draw=current_winning_draw_copy, name=current_user.firstname)

    # if no winning draw exists, rerender admin page
    flash("No winning draw exists. Please add winning draw.")
    return admin()


# view lottery results and winners
@admin_blueprint.route('/run_lottery', methods=['POST'])
@login_required
@requires_roles('admin')
def run_lottery():
    # get current unplayed winning draw
    current_winning_draw = Draw.query.filter_by(win=True, played=False).first()

    # if current unplayed winning draw exists
    if current_winning_draw:
        # creates a copied draw object which are independent of database.
        current_winning_draw_copy = copy.deepcopy(current_winning_draw)
        # decrypt the copied draw object.
        user = User.query.filter_by(id=current_winning_draw.user_id).first()
        current_winning_draw_copy.view_draw(user.draw_key)
        # get all unplayed user draws
        user_draws = Draw.query.filter_by(win=False, played=False).all()
        results = []

        # if at least one unplayed user draw exists
        if user_draws:

            # update current winning draw as played
            current_winning_draw.played = True
            db.session.add(current_winning_draw)
            db.session.commit()

            # for each unplayed user draw
            for draw in user_draws:

                # get the owning user (instance/object)
                user = User.query.filter_by(id=draw.user_id).first()
                copied_draw = copy.deepcopy(draw)
                decrypted_user_draw = copied_draw.view_draw(user.draw_key)
                # if user draw matches current unplayed winning draw
                if decrypted_user_draw == current_winning_draw_copy.draw:
                    # add details of winner to list of results
                    results.append((current_winning_draw.round, draw.draw, draw.user_id, user.email))

                    # update draw as a winning draw (this will be used to highlight winning draws in the user's
                    # lottery page)
                    draw.match = True

                # update draw as played
                draw.played = True

                # update draw with current lottery round
                draw.round = current_winning_draw.round

                # commit draw changes to DB
                # draw1 = Draw.query.filter_by(id=draw.id).first
                # draw1.match = draw.match
                # draw1.played = draw.played
                # draw1.round = draw.round
                db.session.add(draw)
                db.session.commit()

            # if no winners
            if len(results) == 0:
                flash("No winners.")

            return render_template('admin.html', results=results, name=current_user.firstname)

        flash("No user draws entered.")
        return admin()

    # if current unplayed winning draw does not exist
    flash("Current winning draw expired. Add new winning draw for next round.")
    return admin()


# view last 10 log entries
@admin_blueprint.route('/logs', methods=['POST'])
@login_required
@requires_roles('admin')
def logs():
    with open("lottery.log", "r") as f:
        content = f.read().splitlines()[-10:]
        content.reverse()

    return render_template('admin.html', logs=content, name=current_user.firstname)

lottery/views.py
# IMPORTS
import copy
import logging
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from flask_wtf import form
from sqlalchemy import desc
from app import db, requires_roles
from models import Draw, User

# CONFIG
lottery_blueprint = Blueprint('lottery', __name__, template_folder='templates')


# VIEWS
# view lottery page
@lottery_blueprint.route('/lottery')
@login_required
@requires_roles('user')
def lottery():
    return render_template('lottery.html')


@lottery_blueprint.route('/add_draw', methods=['POST'])
@login_required
@requires_roles('user')
def add_draw():
    submitted_draw = ''
    for i in range(6):
        submitted_draw += request.form.get('no' + str(i + 1)) + ' '
    submitted_draw.strip()

    # create a new draw with the form data.
    new_draw = Draw(user_id=current_user.id, draw=submitted_draw, win=False,
                    round=0, draw_key=current_user.draw_key)

    # add the new draw to the database
    db.session.add(new_draw)
    db.session.commit()

    # re-render lottery.page
    flash('Draw %s submitted.' % submitted_draw)
    return lottery()


# view all draws that have not been played
@lottery_blueprint.route('/view_draws', methods=['POST'])
@login_required
@requires_roles('user')
def view_draws():
    # get all draws that have not been played [played=0]
    playable_draws = Draw.query.filter_by(user_id=current_user.id,
                                          played=False).all()
    # creates a list of copied draw objects which are independent of database.
    playable_draw_copies = list(map(lambda x: copy.deepcopy(x), playable_draws))

    # empty list for decrypted coppied draw objects
    decrypted_playable_draws = []

    # decrypt each copied draw object and add it to decrypted_playable_draws array.
    for p in playable_draw_copies:
        user = User.query.filter_by(id=p.user_id).first()
        p.view_draw(user.draw_key)
        decrypted_playable_draws.append(p)

    # if playable draws exist
    if len(playable_draws) != 0:
        # re-render lottery page with playable draws
        return render_template('lottery.html', playable_draws=decrypted_playable_draws)
    else:
        flash('No playable draws.')
        return lottery()


# view lottery results
@lottery_blueprint.route('/check_draws', methods=['POST'])
@login_required
@requires_roles('user')
def check_draws():
    # get played draws
    played_draws = Draw.query.filter_by(played=True, user_id=current_user.id).all()
    # creates a list of copied draw objects which are independent of database.
    played_draw_copies = list(map(lambda x: copy.deepcopy(x), played_draws))

    # empty list for decrypted coppied draw objects
    decrypted_played_draws = []

    # decrypt each copied post object and add it to decrypted_posts array.
    for p in played_draw_copies:
        user = User.query.filter_by(id=p.user_id).first()
        p.view_draw(user.draw_key)
        decrypted_played_draws.append(p)
    # if played draws exist
    if len(played_draws) != 0:
        return render_template('lottery.html', results=decrypted_played_draws, played=True)

    # if no played draws exist [all draw entries have been played therefore wait for next lottery round]
    else:
        flash("Next round of lottery yet to play. Check you have playable draws.")
        return lottery()


# delete all played draws
@lottery_blueprint.route('/play_again', methods=['POST'])
@login_required
@requires_roles('user')
def play_again():
    delete_played = Draw.__table__.delete().where(Draw.played and Draw.user_id == current_user.id)
    db.session.execute(delete_played)
    db.session.commit()

    flash("All played draws deleted.")
    return lottery()

users/views.py
# IMPORTS
import logging
from functools import wraps
import pyotp
from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import check_password_hash

from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# VIEWS
# view registration
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        pin_key=form.pin_key.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        logging.warning('SECURITY - User registration [%s, %s]', form.email.data, request.remote_addr)

        # sends user to login page
        return redirect(url_for('users.login'))
    # if request method is GET or form not valid re-render signup page
    return render_template('register.html', form=form)


# view user login
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # if session attribute logins does not exist create attribute logins
    if not session.get('logins'):
        session['logins'] = 0
    # if login attempts is 3 or more create an error message
    elif session.get('logins') >= 3:
        flash('Number of incorrect logins exceeded')
    form = LoginForm()

    if form.validate_on_submit():
        # increase login attempts by 1
        session['logins'] += 1

        user = User.query.filter_by(email=form.email.data).first()

        if not user or not check_password_hash(user.password, form.password.data):
            logging.warning('SECURITY - Invalid login attempt [%s, %s]', form.email.data, request.remote_addr)
            # if no match create appropriate error message based on login attempts
            if session['logins'] == 3:
                flash('Number of incorrect logins exceeded')
            elif session['logins'] == 2:
                flash('Please check your login details and try again. 1 login attempt remaining')
            else:
                flash('Please check your login details and try again. 2 login attempts remaining')

            return render_template('login.html', form=form)

        if pyotp.TOTP(user.pin_key).verify(form.pin_key.data):
            # if user is verified reset login attempts to 0
            session['logins'] = 0

            login_user(user)

            user.last_logged_in = user.current_logged_in
            user.current_logged_in = datetime.now()
            db.session.add(user)
            db.session.commit()
            logging.warning('SECURITY - Log in [%s, %s, %s]', current_user.id, current_user.email, request.remote_addr)

            # direct to role appropriate page
            if current_user.role == 'admin':
                return redirect(url_for('admin.admin'))
            else:
                return redirect(url_for('users.profile'))
        else:
            flash("You have supplied an invalid 2FA token!", "danger")

    return render_template('login.html', form=form)


# view user profile
@users_blueprint.route('/profile')
@login_required
@requires_roles('user')
def profile():
    return render_template('profile.html', name=current_user.firstname)


# view user account
@users_blueprint.route('/account')
@login_required
def account():
    return render_template('account.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone)


@users_blueprint.route('/logout')
@login_required
def logout():
    logging.warning('SECURITY - Log out [%s, %s, %s]', current_user.id, current_user.email, request.remote_addr)
    logout_user()
    return redirect(url_for('index'))

templates/503.html
{% extends "base.html" %}

{% block content %}

     <h2 class="title is-2">Service Unavailable</h2>

{% endblock %}

templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="column is-6 is-offset-3">
    <h3 class="title">Your Account</h3>
    <div class="box">
        <table class="table">
        <tbody>
            <tr>
                <th>Account No.</th>
                <th>{{ acc_no }}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{ email }}</th>
            </tr>
            <tr>
                <th>First Name</th>
                <th>{{ firstname }}</th>
            </tr>
            <tr>
                <th>Last Name</th>
                <th>{{ lastname }}</th>
            </tr>
            <tr>
                <th>Phone No.</th>
                <th>{{ phone }}</th>
            </tr>
        </tbody>
        </table>
    </div>
</div>


{% endblock %}

templates/admin.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='rng.js') }}"></script>
    <h3 class="title is-3">Lottery Web Application Admin
    </h3>
    <h4 class="subtitle is-4">
        Welcome, {{ name }}
    </h4>

    <div class="column is-10 is-offset-1">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}


        <h4 class="title is-4">Current Users</h4>
        <div class="box">
            {% if current_users %}
                <div class="field">
                    <table class="table">
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                            <th>Phone No.</th>
                            <th>Role</th>
                        </tr>
                        {% for user in current_users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.firstname }}</td>
                                <td>{{ user.lastname }}</td>
                                <td>{{ user.phone }}</td>
                                <td>{{ user.role }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
            <form method="POST" action="/view_all_users">
                <div>
                    <button class="button is-info is-centered">View All Users</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2">
        <h4 class="title is-4">Create Winning Draw</h4>
        <div class="box">
            <form method="POST" action="/create_winning_draw">
                <div class="columns is-multiline is-centered">
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no1" id="no1" placeholder="value 1">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no2" id="no2" placeholder="value 2">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no3" id="no3" placeholder="value 3">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no4" id="no4" placeholder="value 4">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no5" id="no5" placeholder="value 5">
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no6" id="no6" placeholder="value 6">
                    </div>
                </div>
                <div class="field">
                    <button type="button" class="button is-info is-centered" onclick="luckyDip()">Lucky
                        Dip
                    </button>
                </div>
                <div>
                    <button class="button is-info is-centered">Submit Winning Draw</button>
                </div>

            </form>
        </div>
    </div>
    <div class="column is-4 is-offset-4">
        <h4 class="title is-4">Current Winning Draw</h4>
        <div class="box">
            {% if winning_draw %}
                <div class="field">
                    <p>Round {{ winning_draw.round }}</p>
                    <p>{{ winning_draw.draw }}</p>
                </div>
            {% endif %}
            <form method="POST" action="/view_winning_draw">
                <div>
                    <button class="button is-info is-centered">View Winning Draw</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2">
        <h4 class="title is-4">Run Lottery</h4>
        <div class="box">
            {% if results %}
                <div class="field">
                    {% for result in results %}
                        <p>{{ result }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="POST" action="/run_lottery">
                <div>
                    <button class="button is-info is-centered">View Winners</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-8 is-offset-2" id="test">
        <h4 class="title is-4">Security Logs</h4>
        <div class="box">
            {% if logs %}
                <div class="field">
                <table class="table">
                    <tr>
                        <th>Last 10 Security Log Entries</th>
                    </tr>
                    {% for entry in logs %}
                        <tr>
                            <td>{{ entry }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            <form method="POST" action="/logs">
                <div>
                    <button class="button is-info is-centered">View Logs</button>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='lottery.css') }}">

</head>

<body>


    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                       <div class="navbar-end">
                            <a href="{{ url_for('index') }}" class="navbar-item">
                               Home
                            </a>
                           {% if current_user.is_authenticated and current_user.role=='user' %}
                                <a href="{{ url_for('users.profile') }}" class="navbar-item">
                                    Profile
                                </a>
                                <a href="{{ url_for('lottery.lottery') }}" class="navbar-item">
                                    Lottery
                                </a>
                            {% endif %}
                            {% if current_user.is_authenticated and current_user.role=='admin' %}
                                <a href="{{ url_for('admin.admin') }}" class="navbar-item">
                                    Admin
                                </a>
                           {% endif %}
                            {% if not current_user.is_authenticated %}
                                <a href="{{ url_for('users.login') }}" class="navbar-item">
                                    Login
                                </a>
                                <a href="{{ url_for('users.register') }}" class="navbar-item">
                                    Register
                                </a>
                           {% endif %}
                            {% if current_user.is_authenticated %}
                                 <a href="{{ url_for('users.account') }}" class="navbar-item">
                                    Account
                                </a>
                                <a href="{{ url_for('users.logout') }}" class="navbar-item">
                                    Logout
                                </a>
                           {% endif %}
                       </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">Lottery Web Application
</h1>
<h2 class="subtitle">
  CSC2031 Security & Programming Paradigms
</h2>

<p>Muhannad Aldossary ('200533621')</p>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            {% if not session['logins'] or session['logins'] < 3 %}
                <form method="POST">
                    <div class="field">
                        {{ form.csrf_token() }}
                        <div class="control">
                            {{ form.email(class="input", placeholder="Username") }}
                            {% for error in form.email.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.password(class="input", placeholder="Password") }}
                            {% for error in form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.pin_key(class="input", placeholder="Time-Based PIN") }}
                            {% for error in form.pin_key.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="button is-info is-centered") }}
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/lottery.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='rng.js')}}"></script>
    <h3 class="title is-3">
        Lottery
    </h3>
    <div class="column is-8 is-offset-2">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        <h4 class="title is-4">Create Draw</h4>
        <div class="box">

            <form method="POST" action="/add_draw">
                <div class="columns is-multiline is-centered">
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no1" id="no1" placeholder="value 1" min="1" max="60" required>
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no2" id="no2" placeholder="value 2" min="1" max="60" required>
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no3" id="no3" placeholder="value 3" min="1" max="60" required>
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no4" id="no4" placeholder="value 4" min="1" max="60" required>
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no5" id="no5" placeholder="value 5" min="1" max="60" required>
                    </div>
                    <div class="column is-one-sixth">
                        <input class="input" type="number" name="no6" id="no6" placeholder="value 6" min="1" max="60" required>
                    </div>
                </div>
                <div class="field">
                    <button type="button" class="button is-info is-centered" onclick="luckyDip()">Lucky
                        Dip
                    </button>
                </div>
                <div class="field">
                    <button class="button is-info is-centered">Submit Draw</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-4 is-offset-4">
        <h4 class="title is-4">Playable Draws</h4>
        <div class="box">
            {% if playable_draws %}
                <div class="field">

                    {# render playable draws #}
                    {% for draw in playable_draws %}
                        <p>{{ draw.draw }}</p>
                    {% endfor %}

                </div>
            {% endif %}
            <form method="POST" action="/view_draws">
                <div>
                    <button class="button is-info is-centered">View Playable Draws</button>
                </div>
            </form>
        </div>
    </div>
    <div class="column is-6 is-offset-3">
        <h4 class="title is-4">Play Lottery</h4>
        <div class="box">
            {% if results %}
                <div class="field">
                    <table class="table">
                        <tr>
                            <th>Round</th>
                            <th>Draw</th>
                            <th>Played</th>
                            <th>Win</th>
                        </tr>

                        {# render results #}
                        {% for draw in results %}
                            <tr>
                                <td>{{ draw.round }}</td>
                                <td>{{ draw.draw }}</td>
                                <td>{{ draw.played }}</td>
                                {% if draw.match %}
                                    <td style="background-color: yellow">{{ draw.match }}</td>
                                {% else %}
                                    <td>{{ draw.match }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}

            {# render check result button if current lottery round not played #}
            {% if not played %}
                <form method="POST" action="/check_draws">
                    <div>
                        <button class="button is-info is-centered">Check Result</button>
                    </div>
                </form>
            {% else %}
                {# render play again button if current lottery round has been played #}
                <form method="POST" action="/play_again">
                    <div>
                        <button class="button is-info is-centered">Play Again</button>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
  Welcome, {{ name }}
</h1>

{% endblock %}